EMBEDDING_MODEL: "intfloat/e5-small-v2"
COLLECTION_NAME: "parliamentary_meeting_notes"
# GENERATION_MODEL: "gemini-2.5-flash"
GENERATION_MODEL: "gpt-5-nano"
JUDGE_MODEL: "gpt-4o-mini"

# Evaluation Configuration
EVALUATION_RUN_NAME: "Basic_run_with_Sentence_Splitter"
EVALUATION_RUN_DESCRIPTION: "Baseline run with Sentence Splitter with 400 Chunks"
EVALUATION_RESULTS_PATH: "evaluation/results"
EVALUATION_DATASET_PATH: "evaluation/dataset/rag_eval_dataset.json"
GOLDEN_DATASET_PATH: "evaluation/dataset/parliament_rag_golden_dataset.json"
TOP_K_VALUES: [2, 4, 6, 8, 10, 12, 20]
MAX_NODES_FOR_EVAL: null  # null means use all nodes
